import express, { Request, Response } from 'express';
import dotenv from "dotenv";
import cors from "cors";
import cookieParser from "cookie-parser";
import axios from 'axios';

dotenv.config();

const app = express();
const port = 8000;

const SOLR_URL = process.env.SOLR_URL || 'http://localhost:8983/solr/football_core/select';

app.use(cors({
    origin: "http://localhost:5173",
    credentials: true,
}));

app.use(express.json());
app.use(cookieParser());

// Define the interface for TypeScript safety
interface NestedComment {
    text: string;
    sentiment: 'positive' | 'negative' | 'neutral';
}

/**
 * FINAL PARSER: Splits Python lists by looking for content inside '...' or "..."
 * This version avoids backreferences (\1) to prevent TypeScript Octal errors.
 */
const parseComments = (raw: string): string[] => {
    if (!raw || raw === '[]' || typeof raw !== 'string') return [];
    
    const result: string[] = [];
    // Catch content in 'single quotes' OR "double quotes" separately
    const regex = /'((?:\\.|[^'])*)'|"((?:\\.|[^"])*)"/gs;
    let match;

    while ((match = regex.exec(raw)) !== null) {
        // match[1] is content from single quotes, match[2] is from double quotes
        let content = (match[1] || match[2])
            .replace(/\\'/g, "'")
            .replace(/\\"/g, '"')
            .replace(/\\n/g, ' ')
            .replace(/\\r/g, '')
            .trim();
        
        if (content && content !== "[]") result.push(content);
    }
    return result;
};


app.post('/search', async (req: Request, res: Response) => {
    try {
        const { query, source, start_date, end_date } = req.body;

        // TARGETED SEARCH: Title, Content, Author, Subreddit
        let q = '*:*';
        if (query) {
            q = `(title:("${query}") OR content:("${query}") OR author:("${query}") OR subreddit:("${query}"))`;
        }

        const params = new URLSearchParams();
        params.append('q', q);
        params.append('wt', 'json');
        params.append('rows', '50');
        params.append('sort', 'num_comments desc'); // Rank by discussion volume

        if (source) params.append('fq', `subreddit:"${source}"`);
        if (start_date || end_date) {
            const start = start_date ? `${start_date}T00:00:00Z` : '*';
            const end = end_date ? `${end_date}T23:59:59Z` : '*';
            params.append('fq', `datetime:[${start} TO ${end}]`);
        }

        const solrResponse: any = await axios.get(SOLR_URL, { params });
        const docs = solrResponse.data.response.docs;

        /* old implementation fastapi ---
        const posts = await Promise.all(docs.map(async (doc: any) => {
            let nestedComments: NestedComment[] = [];
            const rawCommentsStr = doc.comments_raw;

            if (rawCommentsStr) {
                // const commentTexts = parseComments(rawCommentsStr);
                let nestedComments = [];
                
                if (doc.comments_scored > 0) {
                    try {
                        const pythonResponse = await axios.post('http://localhost:8001/analyze', {
                            texts: commentTexts
                            
                        });
                        
                        nestedComments = pythonResponse.data;
                    } catch (err) {
                        console.error(`Python ML Service unavailable for doc ${doc.id}`);
                        // Fallback if Python server is off or crashes: default everything to neutral
                        nestedComments = commentTexts.map(text => ({ text, sentiment: 'neutral' }));
                    }
                }
            }

            return {
                id: doc.id,
                author: doc.author,
                title: doc.title,
                content: doc.content || "",
                timestamp: doc.datetime ? new Date(doc.datetime).toLocaleString() : "Unknown",
                source: doc.subreddit,
                team: doc.author_flair || "General",
                nestedComments: nestedComments 
            };
        }));
        --------------------------------------------------- */
        const posts = docs.map((doc: any) => {
            let nestedComments: NestedComment[] = [];

            // Directly parse the JSON string generated by the Python batch script
            if (doc.comments_scored) {
                try {
                    nestedComments = typeof doc.comments_scored === 'string' 
                        ? JSON.parse(doc.comments_scored) 
                        : doc.comments_scored;
                } catch (err) {
                    console.error("Failed to parse pre-scored comments for doc", doc.id);
                }
            }

            return {
                id: doc.id,
                author: doc.author,
                title: doc.title,
                content: doc.content || "",
                timestamp: doc.datetime ? new Date(doc.datetime).toLocaleString() : "Unknown",
                source: doc.subreddit,
                team: doc.author_flair || "General",
                nestedComments: nestedComments 
            };
        });
        
        console.log("SENDING POSTS:", JSON.stringify(posts.map((p: any) => ({ id: p.id, numComments: p.nestedComments.length })).slice(0, 5)));
        // ----------------------------------

        res.json({ posts: posts, recordCount: solrResponse.data.response.numFound });

    } catch (error: any) {
        console.error("Backend Error:", error.message);
        res.status(500).json({ error: "Search failed" });
    }
});

app.listen(port, () => console.log(`Backend running on port ${port}`));